import SwiftUI

struct Dinner3: View {
    var body: some View {
        VStack{
            Text("One-Pot Creamy Tuscan Pasta")
                .font(.largeTitle)
                .fontWeight(.bold)
            Image("pasta")
                .resizable()
                .frame(width: 300, height: 200)
            Text("Ingredients:")
                .fontWeight(.bold)
                .font(.headline)
            Text("- 2 tablespoons unsalted butter")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1 shallot, minced")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 4 garlic cloves, minced")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 2 tablespoons tomato paste")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1 teaspoon dried oregano")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1 teaspoon paprika")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 2 cups chicken broth")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1 cup whole milk, or more as needed")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 8 oz penne pasta")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1 cup cherry tomatoes, halved")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1/2 cup sun-dried tomatoes in olive oil, julienne-style, drained")
                .font(.caption)
                .foregroundColor(.white)
            Text("- kosher salt, to taste")
                .font(.caption)
                .foregroundColor(.white)
            Text("- freshly ground black pepper, to taste")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1 cup fresh baby spinach")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1/2 cup grated parmesan cheese")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 2 tablespoons chopped fresh Italian parsley")
                .font(.caption)
                .foregroundColor(.white)
            
            Text("Steps:")
                .fontWeight(.bold)
                .font(.headline)            
            Text("1. In a large skillet, add the butter, shallot, and garlic; cook, stirring frequently, for 3-4 minutes, until softened.")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("2. Add the tomato paste, oregano, and paprika. Cook and stir for 2 minutes, or until the tomato paste starts to darken.")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("3. Add the chicken broth, milk, pasta, cherry tomatoes, and sun-dried tomatoes; season with salt and pepper.")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("4. Bring to a boil, then reduce heat and simmer, stirring occasionally, for 18-20 minutes, until the pasta is tender yet firm to the bite.")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("5. Remove from heat and stir in the spinach and Parmesan cheese until the spinach is wilted and the cheese is incorporated")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("6. If the mixture is too thick, add more milk as needed until the desired consistency is reached.")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("7. Garnish with parsley and serve hot.")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("8. Enjoy!")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
        }
        .padding()
        .background(Color.green)
        .cornerRadius(20)
        .padding()
    }
    
}




