//
//  Dinner1.swift
//  Recipes 4 you
//
//  Created by Santo Mathew on 4/23/24.
//

import SwiftUI

struct Dinner1: View {
    var body: some View {
        ScrollView{
            VStack{
                Text("Birria Tacos")
                    .font(.largeTitle)
                    .fontWeight(.bold)
                Image("Birria-Tacos-114")
                    .resizable()
                    .frame(width: 200, height: 100)
                Text("Ingredients:")
                    .fontWeight(.bold)
                    .font(.headline)
                Text("- 2 Lb ground beef")
                    .font(.caption)
                    .foregroundColor(.white)
                Text("- 1 Chopped onion")
                    .font(.caption)
                    .foregroundColor(.white)
                Text("- 2 Tbsp minced garlic")
                    .font(.caption)
                    .foregroundColor(.white)
                Text("- 1 Tsp each of salt and pepper")
                    .font(.caption)
                    .foregroundColor(.white)
                Text("- 1/2 Tsp cayenne")
                    .font(.caption)
                    .foregroundColor(.white)
                Text("- 4 Tsp chilli powder")
                    .font(.caption)
                    .foregroundColor(.white)
                Text("- 2 Tsp each of cumin and dried cilantro")
                    .font(.caption)
                    .foregroundColor(.white)
                Text("- 1 1/2 cups of beef broth")
                    .font(.caption)
                    .foregroundColor(.white)
                Text("- White corn tortillas")
                    .font(.caption)
                    .foregroundColor(.white)
                Text("- 1 tbsp oil")
                    .font(.caption)
                    .foregroundColor(.white)
                Text("- Shredded monteery jack cheese")
                    .font(.caption)
                    .foregroundColor(.white)
                Text("- Taco toppings(sour cream, taco sauce, pico de gallo,  shredded lettuce)")
                    .font(.caption)
                    .foregroundColor(.white)
                
                Text("Steps:")
                    .font(.headline)
                    .fontWeight(.bold)
                
                Text("1. Add Ground beef and a chopped onion to a Killet over medium high heat")
                    .font(.caption)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                Text("2. once beef is cooked through drain the grease grease")
                    .font(.caption)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                Text("3. add all seasonings and beef broth.")
                    .font(.caption)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                Text("4. bring a boil then lower the heat")
                    .font(.caption)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                Text("5. cover and let simmer for about 20 minutes untill the  liquid has reduced")
                    .font(.caption)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                Text("6. in a Separate  pan, heat the skillet over medium heat and add som e oil to the skillet")
                    .font(.caption)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                Text("7. Lay out a few of the tortillas and tip them with shredded monterey jack cheese")
                    .font(.caption)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                Text("8. Top each one with a spoonful of taco meat")
                    .font(.caption)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                Text("9. Fold the tortillas over and cook on both sides untill golden brown and crispy")
                    .font(.caption)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                Text("10. Lay the tacos out on paper towels to absorb any extra grease")
                    .font(.caption)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
                Text("11. Top tacos with your favorite topping and enjoy!")
                    .font(.caption)
                    .foregroundColor(.white)
                    .multilineTextAlignment(.center)
            }
        }
        .padding()
        .background(Color.green)
        .cornerRadius(20)
        .padding()
    }
    
}
