import SwiftUI

struct Drink2: View {
    var body: some View {
        VStack{
            Text("Horchata")
                .font(.largeTitle)
                .fontWeight(.bold)
            Image("Horchata-recipe")
                .resizable()
                .frame(width: 200, height: 100)
            Text("Ingredients:")
                .fontWeight(.bold)
                .font(.headline)
            Text("1 cup of any uncooked white rice")
                .font(.caption)
                .foregroundColor(.white)
            Text("2 cinnamon sticks")
                .font(.caption)
                .foregroundColor(.white)
            Text("1 can each of evaporated milk")
                .font(.caption)
                .foregroundColor(.white)
            Text("Ground cinnamon to garnish(optional)")
                .font(.caption)
                .foregroundColor(.white)
            Text(" 1/2 teaspoon vanilla (optional)")
                .font(.caption)
                .foregroundColor(.white)
            Text("Steps:")
                .fontWeight(.bold)
                .font(.headline)
            Text("1. Wash and drain the rice")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("2. Place the rice, cinnamon stick and 4 cups of water into a bowl.")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("3. Cover the bowl and refrigerate overnight or a minimum of 4 hours.")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("4. Add 1/2 of the rice and 1/2 of the soaking water and some of the cinnamon stick in a blender.")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("5. Puree untill its very smooth and forms a paste like texture. About 4 minutes long.")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("6. Using a very fine strainer pour the mixture over a pitcher  starin out as much liquid as possible, pushing on the solids with a spatuala or spoon. Repeat this process for the rest of the rice and cinnamon mixture.")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            Text("7. Stir in the milks, vanilla and 4 cups of water. Stir well. taste and add more sugar or water if needed. Chill and stir before serving over ice. ")
                .font(.caption)
                .foregroundColor(.white)
                .multilineTextAlignment(.center)
            
        }
        .padding()
        .background(Color.orange)
        .cornerRadius(20)
        .padding()
    }
}
