//
//  Snack1.swift
//  Recipes 4 you
//
//  Created by Santo Mathew on 4/23/24.
//

import SwiftUI

struct Snack1: View {
    var body: some View {
        VStack{
            Text("Cookie")
                .font(.largeTitle)
                .fontWeight(.bold)
            Image("cookie")
                .resizable()
                .frame(width: 200, height: 100)
            Text("Ingredients:")
                .fontWeight(.bold)
                .font(.headline)
                
                         
            Text("- 1 cup of unsalted butter")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 2 1/2 all purpose flour")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1 teaspoon baking powder")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 3/4 teaspoon kosher salt")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1/2 teaspoon baking soda")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1 cup packed dark brown sugar")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1/2 cup granulated sugar")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 2 large eggs")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 2 teaspoon vanilla extract")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 3/4 cup bittersweet chocalate chips")
                .font(.caption)
                .foregroundColor(.white)
            Text("- morsels or discs")
                .font(.caption)
                .foregroundColor(.white)
            Text("- 1 1/4 bittersweet chocolate bar")
                .font(.caption)
                .foregroundColor(.white)
            Text("- chopped, 1/2 teaspoon flasy sea salt")
                .font(.caption)
                .foregroundColor(.white)
            Text("- such as maldon")
                .font(.caption)
                .foregroundColor(.white)
                
            
            Text("Steps:")
                .font(.headline)
                .fontWeight(.bold)
                
            Text("1. Whisk the flour, baking soda, cornstarch, and salt together in a large bowl")
                .font(.caption)
                .foregroundColor(.white)
            Text("2. Set aside.In a medium bowl, whisk the melted butter, brown sugar, and granulated sugar together until no brown sugar lumps remain")
                .font(.caption)
                .foregroundColor(.white)
            Text("3. Whisk in the egg and egg yolk")
                .font(.caption)
                .foregroundColor(.white)
            Text("4. Finally, whisk in the vanilla extract. The mixture will be thin")
                .font(.caption)
                .foregroundColor(.white)
            Text("5. Pour into dry ingredients and mix together with a large spoon or rubber spatula. The dough will be very soft, thick, and appear greasy.")
                .font(.caption)
                .foregroundColor(.white)
            Text("6. Fold in the chocolate chips. The chocolate chips may not stick to the dough because of the melted butter, but do your best to combine them")
                .font(.caption)
                .foregroundColor(.white)
            Text("7. Cover the dough tightly and chill in the refrigerator for at least 2–3 hours or up to 3 days. I highly recommend chilling the cookie dough overnight for less spreading")
                .font(.caption)
                .foregroundColor(.white)
            Text("8. Take the dough out of the refrigerator and allow it to slightly soften at room temperature for 10 minutes")
                .font(.caption)
                .foregroundColor(.white)
            Text("9. Using a cookie scoop or Tablespoon measuring spoon, measure 3 scant Tablespoons (about 2 ounces, or 60g) of dough for XL cookies or 2 heaping Tablespoons (about 1.75 ounces, or 50g) of dough for medium/large cookies. ")
                .font(.caption)
                .foregroundColor(.white)
            Text("10. Roll into a ball, making sure the shape is taller rather than wide—almost like a cylinder. This helps the cookies bake up thicker")
                .font(.caption)
                .foregroundColor(.white)
            Text("11. Repeat with remaining dough")
                .font(.caption)
                .foregroundColor(.white)
            Text("12. Place 8–9 balls of dough onto each cookie sheet")
                .font(.caption)
                .foregroundColor(.white)
            Text("13. Preheat oven to 325F")
                .font(.caption)
                .foregroundColor(.white)
            Text("14. line large baking sheets with parchment paper or silicone baking mats. Set aside")
                .font(.caption)
                .foregroundColor(.white)
            Text("15. Using a cookie scoop or tablespoon measuring spoon, measure 3 scant tablespoons of dough for XL cookie or 2 heaping tablespoons of dough  for medium/large cookies. ")
                .font(.caption)
                .foregroundColor(.white)
            Text("16. Roll into a ball, making sure the shape is taller  rather than wide almost like a cylinder. this helps the cookies bake up thicker.")
                .font(.caption)
                .foregroundColor(.white)
            Text("17. Repeat with remaiining dough place 8-9 balls of dough onto each cookie sheet")
                .font(.caption)
                .foregroundColor(.white)
            Text("18. bake the cokkies for 12-13 minutes or untill the edges are very lightly browned. the centers will look very soft, but the cookies will continue to set as they cool.")
                .font(.caption)
                .foregroundColor(.white)
            Text("19. cool on the baking sheet for 10minutes. meanwhile. press a few extra chocolate chips intp the tops of the warm cookies. this is optional and only for looks after")
                .font(.caption)
                .foregroundColor(.white)
            Text("20. after 10 minutes of cooling on the baking sheets, transfer cookies to wire rack to cool completely. cookies stay fresh covered at room temperature for up to 1 week.")
                .font(.caption)
                .foregroundColor(.white)
        }
        .padding()
        .background(Color.yellow)
        .cornerRadius(20)
        .padding()
    }
    
}

#Preview {
    Snack1()
}
